[time]
disabled = false
style = "bold green"
time_format = "%T"
format = "[$time]($style) "

[status]
style = "blue"
symbol = "ğŸ’£"
format = "[$symbol]($style) "
#disabled = true

[directory]
fish_style_pwd_dir_length = 1

[python]
symbol = "ğŸ "

[java]
symbol = "ğŸ—¡  "
style = "bold green"
format = "[${symbol}(${version} )]($style)"

[docker_context]
format = "[ğŸ‹ $context](blue bold)"

[scala]
symbol = "âš”ï¸  "
format = "[${symbol}(${version} )]($style)"

[aws]
disabled = true

[nodejs]
detect_extensions = [ ]
detect_files = ["package.json", ".node-version"]
