# Replace the "â¯" symbol in the prompt
[character]      # The name of the module
success_symbol = "[â®](bold green)"     # The "symbol" segment is being set to "âœ"
error_symbol = "[â®](bold red)"     # The "symbol" segment is being set to "âœ"
vicmd_symbol = "[â®](bold green)"
[time]
disabled = false
style = "bold green"
time_format = "%T"
format = "[$time]($style) "

[python]
symbol = "ğŸ "
[java]
symbol = "âš”ï¸  "
